---
version: 2
updates:
- package-ecosystem: npm
  directory: /
  schedule:
    interval: daily
  ignore:
  - dependency-name: react
    versions: [">=19.0.0"]
  - dependency-name: react-dom
    versions: [">=19.0.0"]
  - dependency-name: cypress
    versions: [">=11.0.0"]
  - dependency-name: "@simonsmith/cypress-image-snapshot"
    versions: [">=10.0.0"]
  - dependency-name: "eslint-plugin-cypress"
    versions: [">=5.0.0"]
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
  target-branch: develop
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  commit-message:
    prefix: chore
    include: scope
  target-branch: develop
