---
name: CI
on:
- push
- pull_request
env:
  PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
jobs:
  ci:
    name: CI
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      deployments: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: Setup cache
      uses: actions/cache@v4.2.3
      with:
        path: |
          ~/.npm
          ~/.cache
        key: v4-${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          v4-${{ runner.os }}-npm-
    - name: Setup Node.js
      uses: actions/setup-node@v4.4.0
      with:
        node-version-file: .nvmrc
    - name: Install dependencies
      run: npm ci
    - name: Run checks
      run: xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" npx run-s --npm-path npm lint spellcheck test
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    - name: Upload coverage report
      uses: codecov/codecov-action@v5.4.3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy
      uses: cloudflare/wrangler-action@v3
      with:
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        preCommands: npm run build
        command: pages deploy public --project-name=ma-rtin-foo
